export interface Point {
  x: number;
  y: number;
}

export enum PlayerRole {
  OFFENSE = 'OFFENSE',
  DEFENSE = 'DEFENSE'
}

export interface Player {
  id: string;
  label: string; // e.g., "QB", "C", "WR"
  role: PlayerRole;
  x: number; // Percentage 0-100
  y: number; // Percentage 0-100
  route: Point[]; // Array of points for the route
  color: string;
}

export interface Play {
  id: string;
  name: string;
  formation: string;
  tags: string[];
  notes: string;
  players: Player[];
  createdAt: number;
  updatedAt: number;
  aiInsights?: string; // Generated by Gemini
}

export enum ViewMode {
  PLAYBOOK = 'PLAYBOOK',
  EDITOR = 'EDITOR',
  VIEW = 'VIEW'
}
